### ISSUE TITLE
set up hosting with github pages

### ISSUE THREAD

**Issue by emilyhopkins** [DDMAL/linkedmusic-website#10]
serve site as-is with GitHub pages

**Comment by emilyhopkins** [comment]
https://docs.github.com/en/pages/setting-up-a-github-pages-site-with-jekyll/creating-a-github-pages-site-with-jekyll

**Comment by emilyhopkins** [comment]
https://docs.github.com/en/pages/getting-started-with-github-pages/configuring-a-publishing-source-for-your-github-pages-site#choosing-a-publishing-source

**Comment by napulen** [comment]
The site won't be served until `Pages` is set up in the settings of the repo.

**Comment by emilyhopkins** [comment]
Yes, I thought that was the standard way to deploy GitHub pages sites? Is this the same as using GitHub actions?
Where you just go Settings > Pages and then point to the branch you want for the site

**Comment by napulen** [comment]
The settings are the standard way to serve GitHub pages, assuming that the content of the branch is the HTML content.

Ich was referring to the automatic deployment using gh-actions for the cases where you need to *build* the website first, then serve the generated output in a different branch.

As GitHub already *builds* jekyll sites by default, this process is actually abstracted from us, so there is no need for GitHub actions. Having the jekyll project is enough for GitHub to figure it out and render the website. Essentially, they run the `bundle exec jekyll build` for us.

**Comment by emilyhopkins** [comment]
OK, sounds good! Thanks for clarifying!

**Comment by napulen** [comment]
The site is running on: https://ddmal.music.mcgill.ca/linkedmusic-website/

There are some issues with the urls of assets and static resources.
