### ISSUE TITLE
set up CNAME to use URL

### ISSUE THREAD

**Issue by emilyhopkins** [DDMAL/linkedmusic-website#11]

**Comment by emilyhopkins** [comment]
https://docs.github.com/en/pages/configuring-a-custom-domain-for-your-github-pages-site/managing-a-custom-domain-for-your-github-pages-site

**Comment by fujinaga** [comment]
It may be helpful to look at: https://github.com/DDMAL/MIRAI

**Comment by emilyhopkins** [comment]
Set up with EasyDNS

Had to re-build site so URLs would resolve properly to serve over HTTPS making sure it was set to production -- so like this:
jekyll build JEKYLL_ENV=production

also see here: https://mademistakes.com/mastering-jekyll/site-url-baseurl/
("Jekyll development and site.url")

**Comment by fujinaga** [comment]
Congratulations!
