### ISSUE TITLE
Inconsistent resolution of urls in production site

### ISSUE THREAD

**Issue by napulen** [DDMAL/linkedmusic-website#12]
The production site is running here: https://ddmal.music.mcgill.ca/linkedmusic-website/

The content is not rendered properly, because some resources are not pointing to the correct url.

For example, the html is looking for: 
- https://ddmal.music.mcgill.ca/assets/LM_LogoTransparentWhite1.png

which throws a 404, instead, it should be looking for:
- https://ddmal.music.mcgill.ca/linkedmusic-website/assets/LM_LogoTransparentWhite1.png

**Comment by napulen** [comment]
This is related to the `url` and `baseurl` variables in the `_config`:

https://github.com/DDMAL/linkedmusic-website/blob/962f69e9920dc05c57a5e36fb9e7e65e837fac9d/_config.yml#L10-L11

This is not an issue in development, because the root is always `localhost:<port>/`, but in production, the root of `ddmal.music.mcgill.ca/` is not the right place to look for these assets.

I already tried setting the `baseurl` to `https://ddmal.music.mcgill.ca/linkedmusic-website/`, which I thought would solve everything, but it didn't.

I also don't understand the need for `url` and `baseurl`. Usually, people only use `baseurl`. Is there some documentation about this?

**Comment by emilyhopkins** [comment]
I can take a look. this seems promising: https://mademistakes.com/mastering-jekyll/site-url-baseurl/

**Comment by napulen** [comment]
Yes, thanks!

I also reached the same conclusion looking at the default `_config` generated from `jekyll new .`:

It has this on the `_config`

```
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
```

**Comment by emilyhopkins** [comment]
I think I fixed it, does it work for you too? https://ddmal.music.mcgill.ca/linkedmusic-website/
obviously I still want to fix the theme so the nav bar isn't identical to the SIMSSA site but at least it's rendering correctly now

added this for url:                 'https://ddmal.music.mcgill.ca/linkedmusic-website'
(no trailing slash)

then fixed variable name in head.html

**Comment by napulen** [comment]
So, for this site (on production), this should be:

baseurl: "/linkedmusic-website"
url: "https://ddmal.music.mcgill.ca"

**Comment by napulen** [comment]
> I think I fixed it, does it work for you too? https://ddmal.music.mcgill.ca/linkedmusic-website/
> obviously I still want to fix the theme so the nav bar isn't identical to the SIMSSA site but at least it's rendering correctly now
> 
> added this for url: 'https://ddmal.music.mcgill.ca/linkedmusic-website'
> (no trailing slash)
> 
> then fixed variable name in head.html

Yeah, it works

**Comment by emilyhopkins** [comment]
Yay! Ok, I will try updating url and baseurl as you suggested
thanks for noticing and for your help with this!

(FWIW the SIMSSA site has nothing in either spot! very mysterious)

**Comment by emilyhopkins** [comment]
How important is it to have the baseurl and url separate like this
baseurl: "/linkedmusic-website"
url: "https://ddmal.music.mcgill.ca"

Because most of the site.url variables are set up such that this change breaks them all.
I can fix them but if it's not essential I can also leave it as
url: 'https://ddmal.music.mcgill.ca/linkedmusic-website'
and nothing else will break...

What do you think?

**Comment by napulen** [comment]
> Yay! Ok, I will try updating url and baseurl as you suggested
> thanks for noticing and for your help with this!

It'd be great just for consistency with jekyll's docs. If that breaks things, then back to your `url` solution, which we already know it works. Good catch on the `main.css` file, by the way!  

> (FWIW the SIMSSA site has nothing in either spot! very mysterious)

Yes. It seems it's because of the domain. SIMSSA's domain is https://simssa.ca/

It seems these problems appear when the site is served within a folder of the host, e.g., ddmal.simssa.ca/**something**/, which is the case for this one but not for the simssa website

**Comment by emilyhopkins** [comment]
OK, I will leave it as-is for now. There are some things I'd like to clean up eventually since there are some weird things in the SIMSSA site that this site is therefore inheriting but they will be a lower priority for now.

Thanks!!

**Comment by napulen** [comment]
Cool

**Comment by fujinaga** [comment]
The new site should be: https://linkedmusic.ca
We can create a link from AWS Route 53 as in simssa.ca (A records: 185.199.108.153, 185.199.109.153, 185.199.110.153, 185.199.111.153)
Or we could use EasyDNS, where the domain names are registered, as in miraiqc.ca (A records: 185.199.108.153 and 185.199.108.153)
