### ISSUE TITLE
Google translate widget

### ISSUE THREAD

**Issue by emilyhopkins** [DDMAL/linkedmusic-website#15]
1. figure out how to add as in https://theglobaljukebox.org/#
2. figure out how to deal with bilingual content on site (can we mark it to not be translated or similar?)

**Comment by emilyhopkins** [comment]
May have to budget for using Google too?

They are pushing browser translation instead (https://support.google.com/chrome/answer/173424?co=GENIE.Platform%3DDesktop&amp;hl=en) and the widget is only free for COVID update non-profit sites (https://developers.google.com/search/blog/2020/05/google-translates-website-translator) and they send everyone else to Google Cloud Translation API (https://cloud.google.com/translate)

(I can look more into pricing for this later)

**Comment by emilyhopkins** [comment]
https://www.coderepublics.com/howto/how-to-google-translate.php

**Comment by emilyhopkins** [comment]
This is done, little bit hacky solution to adding notranslate tags though --
Had to copy HTML from generated site and use that in pages as <notranslate> works in Markdown but breaks other formatting

**Comment by fujinaga** [comment]
When I select a language the top menu disappears.

**Comment by emilyhopkins** [comment]
Since we can't control the appearance of translate, I've modified the header CSS so it no longer gets hidden when the translate option is used.

**Comment by fujinaga** [comment]
Looks good! Thank you.
