### ISSUE TITLE
Change the navbar from VIM to UMIL

### ISSUE THREAD

**Issue by fujinaga** [DDMAL/linkedmusic-website#34]
@kyrieb-ekat Change the navbar menu item from VIM to UMIL.

**Comment by Monalisa98927** [comment]
Done in https://github.com/DDMAL/linkedmusic-website/commit/7d02b3e5d0cd7458e2f2cb2408ea51c15f33e0f4. Can we close this issue? @fujinaga

**Comment by fujinaga** [comment]
Yes, you can close this issue.

On May 24, 2024, at 22:26, Kun Fang ***@***.***> wrote:

﻿

Done in 7d02b3e<https://github.com/DDMAL/linkedmusic-website/commit/7d02b3e5d0cd7458e2f2cb2408ea51c15f33e0f4>. Can we close this issue? @fujinaga<https://github.com/fujinaga>
