### ISSUE TITLE
Edit the content of the VIM (UMIL) page

### ISSUE THREAD

**Issue by fujinaga** [DDMAL/linkedmusic-website#35]
@kyrieb-ekat Edit the content of the VIM (UMIL) page: [https://github.com/DDMAL/linkedmusic-website/blob/main/vim/index.html](url)

**Comment by Monalisa98927** [comment]
Done in https://github.com/DDMAL/linkedmusic-website/commit/ba18dfd30f8a1084255f5c9a1b0f96df6e41fc7a and https://github.com/DDMAL/linkedmusic-website/commit/1f8d3764c5026a8895dcfc9b3dc656c552284670. Can we close this issue as well? @fujinaga

**Comment by fujinaga** [comment]
Yes, you can close this issue.
Looking good!

On May 24, 2024, at 22:27, Kun Fang ***@***.***> wrote:

﻿

Done in ba18dfd<https://github.com/DDMAL/linkedmusic-website/commit/ba18dfd30f8a1084255f5c9a1b0f96df6e41fc7a> and 1f8d376<https://github.com/DDMAL/linkedmusic-website/commit/1f8d3764c5026a8895dcfc9b3dc656c552284670>. Can we close this issue as well? @fujinaga<https://github.com/fujinaga>
